### ISSUE TITLE
Long term caching with chunkhash

### ISSUE THREAD

**Issue by jtmthf** [reactql/cli#11]
One feature that would be great to have is long-term caching of chunks by using webpack's `chunkhash` feature. On the browser production build, output files would be renamed to something like `[name].[chunkhash].js`. The consequence is that file names are not predictable anymore so that on the server side render, the webpack stats would need to be read to get the file paths of the javascript files.

**Comment by leebenson** [comment]
Having some caching strategy for vendor chunks would be great. I like the sound of this in theory - I've seen implementations of reading the webpack output to figure this out. It's probably not that big of a deal to have dynamic files, except for maybe factoring that into the deployment strategy so that old versions that no longer exist aren't being called on.

Is this something you've already implemented @jtmthf? I'd be open to PRs, or happy to explore it myself if wanted.

**Comment by leebenson** [comment]
Sorry @jtmthf, just saw your comment [here](https://github.com/reactql/cli/issues/13#issue-220426392) in which you confirmed you'd be open to PRs - let me know if that's still the case, and I'll keep this open. Thanks!

**Comment by jtmthf** [comment]
I've been exploring how to do this one following [this](https://webpack.js.org/guides/caching/) guide from the webpack docs. I'll be pushing this before #13 due to some overlap of these. In past guides I've read, it's been recommended to keep old assets for a while especially if you're deploying frequently otherwise users with long running sessions might get 404 errors. However, I haven't seen a catch all solution to this yet.

For a small web app that get front end deployments once every few days or weeks, keeping only the previous assets would be fine. For a big app like Facebook and receiving potentially dozens of deployments a day, you'd want to keep all build assets from at least the last 24 hours. I'd be curious to see how various other projects are handling this.
