### ISSUE TITLE
Does ReactQL have a future?

### ISSUE THREAD

**Issue by chasm** [reactql/cli#111]
This looks like a lot of excellent work! Bravo.

That said, no real changes for the past six months, no sponsors, only three contributors, issues unaddressed. Is this a lovely also-ran, or is there a plan to come back to it? Webpack 4 is out and much improved. What about Styled Components?

Whether this will continue or not, I congratulate you on your high quality work and will strive to learn from it. Thanks!

**Comment by leebenson** [comment]
It surely does. 

**TL;DR - ReactQL is being redesigned as a plugin for Launch.js.**

Check out https://github.com/launchjs/app -- it's a new 'generic' universal Webpack 4 framework I've been working on, as the spiritual successor (and upcoming compilation target) to/for ReactQL.

For more background on what led to it (and some of the reasons why there haven't been any specific updates to ReactQL for a while), see [here](https://github.com/reactql/kit/issues/147) and [here](https://github.com/reactql/kit/issues/80)

The three big changes are:

* Bumps to the latest version of everything: Webpack 4, Apollo 2 (with local state instead of Redux, hopefully), React's new Context API, etc.

* Granularity. ReactQL took a kitchen-sink approach to its modules, which is ideal for an out-the-box starter kit, but not so useful when you're trying to change anything. Launch.js was born out of that problem, and is more modular/easier to customise.

* It's now written in Typescript (and continues to work for plain JS, too.) The `Config` API was getting a bit unruly and easy to fat-finger function names, so it's been re-written with Intellisense in mind.

The ReactQL plugin isn't up yet - I'm literally working on it _right now_ - but it will be soon.

**Comment by leebenson** [comment]
Oh and thanks for your kind words, @chasm 😃

**Comment by chasm** [comment]
That's great news! I'd hate to see all this good work go to waste. We devs spend way too much time reinventing the wheel, and CLIs like this are a tremendous benefit. But only if they're maintained, of course. :-)

TypeScript is even better! Ditto for granularity. I will definitely check out the Launch.js. I'm looking to set up an open source project to build a learning management system for my company, and you've pretty much ticked all the boxes here. I'm on a tight timeline, though, to deliver. Hope it's close!

**Comment by leebenson** [comment]
Life feels like string of tight timelines at present, so I hope so too 😄 

I'm actively working on it. It's central to a number of projects I'm working on, so I'm really trying to get it out the door quickly. The ReactQL plugin should be ready in literally a day or two, pending no major blocks.

Another big change I forgot to mention is: Launch.js is an NPM module which can be directly imported/configured in code, so the CLI will be moot going forward. I always liked the CLI (I wanted to emulate a Meteor-like approach to starting a project), but configuring in code makes it redundant, especially since dropping it in is now literally just `import App from "@launch/app";`.

The side-effect is that it's much easier to upgrade a project now without breaking a bunch of stuff-- and maintaining should be at least a bit easier.

**Comment by chasm** [comment]
I'm looking at launchjs now. The code examples look great, but I'm not sure how one would go about trying it out. No CLI, I get. Do I just start with npm init and then install a library? Or am I too early to try it?

**Comment by leebenson** [comment]
Give it a couple of days, and there will be a 'starter kit' example repo.

If you want to get started earlier, just `npm init` a new project, copy over the [tsconfig.json](https://github.com/launchjs/app/blob/master/tsconfig.json) to your new project folder, and `npm  -S @launch/app`.

You should then be able to follow the instructions at the [readme](https://github.com/launchjs/app/blob/master/README.md) to get it going.

This will be made easier (for example, [making tsconfig.json optional](https://github.com/launchjs/app/issues/7)), but for now, the above should get you going.

**Comment by chasm** [comment]
Thank you. I'm going to play with this now. Have passed this conversation on to a few coworkers who might find it interesting.

**Comment by dstroot** [comment]
Looks like the author has moved away from launch.js.  So back to the question at hand - any updates to ReactQL... ?

**Comment by leebenson** [comment]
@dstroot - Not currently. Posted to the ReactQL readme:

>> Not (currently) maintained
>
> I'm taking some time off OSS, and focusing on commercial projects. It's unlikely I'll be making any changes to ReactQL anytime soon, so please know that before basing your next project off of any code you find here.
>
> That's not to say that I'll never update it, just that it's not currently on my radar. Feel free to fork and extend. Enjoy!

ReactQL still works in its current state, but if you're going to use it, I'd recommend upgrading the stack to keep up to date with vulnerabilities, patches, etc.

Or better yet - just roll config that's specific to your project. I no longer recommend boilerplates or frameworks, generally. They have a habit of hiding important implementation details that it's usually better to have a direct grip on.
