### ISSUE TITLE
Replace Airbnb linting with prettier

### ISSUE THREAD

**Issue by arvigeus** [reactql/cli#18]
Airbnb code guide is great, but developer's job is to focus on code, not on code styling. Prettier "just works" and produces nicely formatted code without forcing you to think about formatting.

**Comment by lucasmotta** [comment]
@arvigeus I think Airbnb's linter provides more than just styling rules, it also checks for possible mistakes. Prettier in the other hand, only cares about how your code looks.
So IMO they can both live together, maybe some of the eslint rules for code-style could be disabled then.

**Comment by leebenson** [comment]
I agree with @lucasmotta. I think there's a huge benefit to enforcing linting _during_ the code process, not just afterwards. In bigger teams, it keeps everyone on the same page. In solo teams, it can pick up on obvious goofs like missing commas or uninitialised vars. The eslinter provided also dynamically checks propTypes on components and highlights if something is declared but not used, or vice versa. IMO, these are all invaluable coding aids that I would like to keep.

As for prettier integration, where in the workflow do you think it should fit in? Since prettier outputs a uniform format, it's just as easy (and possibly more useful) to enable it in Atom or another IDE and get prettify-on-save functionality. I could add it as a step to Webpack to prettify on bundle, but then that only happens when you run a corresponding `npm...` command -- arguably, the job of the editor you're writing it in. And there's no sense prettifying bundled code, because that's all minified for production anyway, so bolting it on to the webpack flow probably isn't that useful.

I'll keep this open to thoughts for now.

Somewhat related to #19.

**Comment by arvigeus** [comment]
Airbnb and Prettier disagree on some styling rules - for example 'string' vs "string" and can't be used together (or at least not in their current form)
As for fixing possible mistakes, I think prettier does that. Not totally sure, @lucasmotta, can you provide and example? This could be somehow related to #19, because CRA uses prettier by default and probably eslint-config-react-app contains those checks as well.
As for where prettier could fit, maybe as a [pre-commit step](https://github.com/facebookincubator/create-react-app/pull/1759).

**Comment by leebenson** [comment]
There's [this](https://www.npmjs.com/package/prettier-eslint) that might be useful.

Picking up code goofs _and_ conforming code to a style would be perfect.

**Comment by leebenson** [comment]
I want to create a 'slim' version of the repo shortly that would not have any opinions as far as linting and stylistic choices, so it'd be up to the developer to add in things like prettier.

I'll close this for now.
