### ISSUE TITLE
Use mainstream babel/eslint presets

### ISSUE THREAD

**Issue by arvigeus** [reactql/cli#19]
Babel + Eslint plugins could easily clog package.json with tons of dependencies. Using existing presets like  babel-preset-react-app and eslint-config-react-app provide sane default that are well tested by community

**Comment by leebenson** [comment]
I need to think about this some more. I built this starter kit as a means to share my own best practices, and part of that is an opinionated and feature-rich styleguide.

For me, the combination of Airbnb's guide with the additional allowance of generators, async/await and `for...of` and [some other stuff](https://reactql.org/docs/styleguide) represents an ideal workflow. Some of those choices are practical - I use async/await extensively, so Airbnb's default preset woudn't work... others are personal- multiple React components on a page sometimes make sense. It's a linting guide I've tuned over months of working with this stack, and is something I'm quite interested in sharing. The create-react-app version doesn't accomodate all of those choices, or doesn't go far enough in enforcing others IMO.

I think this might be something to delegate to a dynamic feature in the CLI, that devs can turn on or off. That should be simple due to the advancements made in #10. I'll keep this open and track it for dynamic ESLint on/off.

**Comment by leebenson** [comment]
Per https://github.com/reactql/cli/issues/10#issuecomment-294346583, a 'slim' version of the kit will be available soon that doesn't come bundled with opinionated linting and cuts back on associated packages. This should solve the issue, so I'll close for now.
