### ISSUE TITLE
Zopfli and Brotli Compression

### ISSUE THREAD

**Issue by jtmthf** [reactql/cli#22]
I was investigating using alternative compression methods and compiled these results. Specifically I wanted to test zopfli which is a gzip implementation that is supposed to compress 5% smaller than traditional gzip. I also tested Brotli which is a completely different algorithm that achieves significantly better compression and is getting fairly high support as of now http://caniuse.com/#feat=brotli. Overall the time to run `yarn run build` didn't vary much and is within the margin of error that the difference in compression time is negligible. I think the best option is using Brotli and Zopfli together as the `.br` file is downloaded for the most modern browsers, `.gz` for those that accept gzip, and then the regular file as the least common denominator fallback.

Downsides are that both these algorithms are native-addons and those can still be tricky sometimes for Windows users I've noticed. However, this project already uses native-addons from node-sass anyways so that can be negated. The other problem is that koa-static doesn't support the `Accept-Encoding: Brotli` header just yet, but I and I imagine most others use nginx in prod anyways for static files. I was also going to file a PR for koa-static anyways. Nginx doesn't natively support Brotli yet, but google maintains [ngx_brotli](https://github.com/google/ngx_brotli) for using nginx.

Otherwise opinions on this would be great, along with if these compression options should be configurable or not from the config files. If so, would this type of compression be opt-in or opt-out?

| Algorithm       | reactql-logo.svg | browser.js | vendor.js | style.css | Total  | Time   |
|:---------------:| ---------------- | ---------- | --------- | --------- | ------ | ------ |
| None            | 1.02 kB          | 5.1 kB     | 375 kB    | 778 bytes | 382 kb | NA     |
| Gzip            | 604 bytes        | 2.15 kB    | 110 kB    | 437 bytes | 113 kb | 30.69s |
| Zopfli          | 593 bytes        | 2.13 kB    | 106 kB    | 426 bytes | 109 kb | 26.72s |
| Brotli          | 545 bytes        | 1.86 kB    | 88.7 kB   | 354 bytes | 91 kb  | 23.52s |
| Brotli + Zopfli | 545 bytes        | 1.86 kB    | 88.7 kB   | 354 bytes | 91 kb  | 32.63  |

**Comment by leebenson** [comment]
great stats, thanks for compiling @jtmthf. Once you've filed the koa-static PR and there's a version bump, would you mind dropping a note here? It'd be great to support Brotli out-the-box, and a switch to Zopfil makes sense as it's basically the same `.gz` file with an alternate compressor.

I agree that an upstream service like Nginx is generally better for handling on-the-fly compression - it's written in C and is going to have a far lower overhead than crunching it through several layers of JS libs per request. Even better though is compiling _ahead_ of time, which is obviously what we're doing with gzip and can also do with Brotli. Since we're dealing with static files entirely (apart from the initial HTML render-- which should remain the purview of Nginx et al re: compression), it makes sense to tack this on to the build process and generate a `.br` as well as `.gz`

As your stats have shown, there's barely any overhead to the build process- especially since Zopfli alone seems to shave off an extra few seconds vs the gzip equivalent.

I think this makes sense to put this directly in core, since the appeal should be pretty universal. Other than a few extra kb of disk space per file, there's very few projects that this won't benefit.

**Comment by jtmthf** [comment]
Just to clarify with nginx, the ngx_brotli module is needed to even recognize `Accept-Encoding: br` and to then serve a pre-compressed `.br` file. Otherwise by default, nginx will only serve the `.gz` file assuming the configuration is correct. Might be good to have a section in the docs about deployment to common scenarios.

Also I found that the change for koa-static needs to be in its dependency koa-send, so it might take a few days for the PR chain to work its way back up to here.

**Comment by leebenson** [comment]
Moving this to https://github.com/reactql/kit/issues/3

**Comment by leebenson** [comment]
@jtmthf - see https://github.com/reactql/kit/issues/3#issuecomment-304884982
