### ISSUE TITLE
Why using redux when apollo client manages its own store?

### ISSUE THREAD

**Issue by mairh** [reactql/cli#31]
The initial look at the project seems very promising. However, I am wondering why are you using redux for state/store management when apollo-client uses its own internal store.

Or you just provide redux integration in case someone wants to utilize it, but redux is not necessary in order to build the client side.

**Comment by leebenson** [comment]
Good question, @mairh - I'm sure other devs might be wondering the same.

The reason is touched on very briefly [in this code comment)(https://github.com/reactql/kit/blob/master/kit/lib/redux.js#L15-L16).

It's very common you'll run into the need for application state _outside_ of Apollo/GraphQL.

Say, clicking a button that fires an AJAX request to a non-GraphQL endpoint and needs to do something with the data... or connecting to a Websocket and responding to server events... or even something much more trivial, such as clicking a button and changing a user setting.

There are plenty of times when the data returned from your GraphQL server will only form part of the full picture. Flux is a useful pattern for the rest of the app, too. By setting Redux explicitly (vs. Apollo's implicit use of it), we can easily add our own 'reducers' that are useful to the non-GraphQL parts of our app.

Let me know if you have any other Qs.

**Comment by leebenson** [comment]
Also worth mentioning are [these lines](https://github.com/reactql/kit/blob/master/kit/lib/redux.js#L20-L30) from the same Redux lib.

By going 'explicit', we can fine-tune the kit to enable Redux tools by default, and rehydrate application state across the _full_ store dump - not just Apollo.

**Comment by mairh** [comment]
Excellent answer @leebenson Could you please tell me if everything from apollo store is mapped automatically to the redux store by default?

However, we have the option to create own redux modules (if case we want to).

For e.g (Apolo store)
<img width="673" alt="screen shot 2017-04-18 at 16 53 31" src="https://cloud.githubusercontent.com/assets/4072250/25134199/a818c448-2457-11e7-8a5f-31bb1f5d0a9f.png">

vs Redux store
<img width="789" alt="screen shot 2017-04-18 at 16 53 50" src="https://cloud.githubusercontent.com/assets/4072250/25134216/b1fb0624-2457-11e7-9781-a760bcfad603.png">

**Comment by leebenson** [comment]
@mairh - correct. Redux uses a _single_ store for the entire application, and the Apollo data appears as an `apollo` key on that one store:

<img width="1123" alt="screen shot 2017-04-18 at 14 58 43" src="https://cloud.githubusercontent.com/assets/719722/25134747/4ddd5b06-2448-11e7-8ff4-6dd0871f8b3d.png">

So, you can add additional reducers to Redux that listen to events other than `APOLLO_QUERY_INIT`, etc, and update the store data as needed.

**Comment by ntziolis** [comment]
In order to handle external data requests etc, we leverage apollo's client side resolvers to handle non graphql accessible data sources. This allows us to retain a single pain of glass for communicating across all components and to the server (using a Graphql api). 

I'd like to understand if there are other reasons for using an additional layer like redux if using the approach above.

Link to apollo client side resolvers:
https://www.apollographql.com/docs/link/links/state.html#resolver

**Comment by leebenson** [comment]
@ntziolis - there shouldn't be, no. Per your link:

```
4. Query resolvers are only called on a cache miss. Since the first time you call the query will be a cache miss, you should return any default state from your resolver function.
```

If you're using Apollo to retrieve data from, say, a REST endpoint, then it should be stored in the Apollo cache on initial retrieval. If you have a `<Query>` object that uses that same data later on, it will pull it from cache, rather than re-request it remotely.

If you have more complex needs, you can even create a mutation in [src/graphql/state.ts](https://github.com/leebenson/reactql/blob/master/src/graphql/apollo.ts) that takes the piece of data you care about, and wrap the block in a `<Mutation>` that triggers the mutation query (i.e. putting the data into the local store), which subsequent `<Query>` blocks can pull from using standard GraphQL syntax.

The point being, the local Apollo store is intended to entirely replace Redux, and give you access to it using regular GraphQL.

**Comment by ntziolis** [comment]
Wow. Thank you for this blazing fast and thorough answer. For us its really exiting to see graphql not just being able to unify "to/from" server, but also internal application communication.

**Comment by leebenson** [comment]
My pleasure!
