### ISSUE TITLE
can you see a react-cli for dva-cli?

### ISSUE THREAD

**Issue by 624508914** [reactql/cli#38]
can you see a react-cli for dva-cli?
I hope you can see a  dva-cli

**Comment by leebenson** [comment]
I had to Google [dva-cli[(https://github.com/dvajs/dva-cli); I wasn't familiar with it.

Looking at the [dva](https://github.com/dvajs/dva) project, it seems like a competing framework/starter kit that already has its own CLI and its own concept of routes, models, and components.

I have no plans to support external kits, because the fundamental APIs are very different. The focus on this CLI is the ReactQL [Javascript](https://github.com/reactql/kit) and [Typescript](https://github.com/reactql/kit.ts) versions only.

**Comment by 624508914** [comment]
thank you
