### ISSUE TITLE
Working with unwind

### ISSUE THREAD

**Issue by kajohnsonjd** [reactql/cli#52]
Hi Lee,

Let me first join the chorus of folks thanking you for this stellar project.  Thank you!

My project hit a snag trying to wire up reducers that play nice with the new unwind( ) code in kit/lib/redux.  Although I can imagine you have a lot on your plate, it would be really helpful to have examples and docs for reducers in the unwind array.

**Comment by leebenson** [comment]
Thanks @kajohnsonjd!

I have added a new issue to track documenting `unwind` and reducers at https://github.com/reactql/docs/issues/2

In the meantime, here's how to use them -

1. Make sure your reducers follow the pattern of exporting an object in the same 'shape' as shown in [this example reducer](https://github.com/reactql/kit/blob/master/reducers/counter.js#L22-L39) - i.e. `{name: { state, reducer }}`. The `name` will become the reducer's key, `state` is an object containing the reducer's initial state, and `reducer` is your reduction function.

2. Import the reducers you need [here](https://github.com/reactql/kit/blob/master/kit/lib/redux.js#L19-L20)

3. Insert the import into the `reducers` array [here](https://github.com/reactql/kit/blob/master/kit/lib/redux.js#L28)

That should be all you need to do. You don't need to touch `unwind` - that's just the internal logic for mapping the reducer's shape to the internal Redux implementation.

Note: In future versions, I'm considering how this can be made easier - perhaps by having an API with a `.register()` function, so that reducers can be added on-the-fly instead of having to mess with `kit` code. But for now, this is how it's done.
