### ISSUE TITLE
Could you suporto Join Monster (for SQL)?

### ISSUE THREAD

**Issue by MichelDiz** [reactql/cli#53]
Docs from Join Monster
http://join-monster.readthedocs.io/en/latest/

Adapter for Apollo.
https://github.com/acarl005/join-monster-graphql-tools-adapter

Best Regards.

**Comment by leebenson** [comment]
Thanks, I'll explore adding this - looks useful.

**Comment by leebenson** [comment]
It's likely that in a future version of ReactQL, that GraphQL server support will be brought in-house instead of using a graph.cool endpoint, to demonstrate how to build a full-stack GraphQL implementation.

If SQL is used at that time, this could be a useful adapter. It depends on which SQL library is selected, and how that's implemented - I'll review the options at the time to see if this makes a sensible fit.

Otherwise, of course, you're free to add this to your project any time you want. ReactQL is currently a front-end framework (there is an [example project](https://github.com/reactql/examples/tree/master/graphql-server) containing a GraphQL server) so adding Join Monster is currently a userland exercise rather than landing in ReactQL proper.
