### ISSUE TITLE
\AppData\Roaming\npm\node_modules\reactql\cli\index.js

### ISSUE THREAD

**Issue by eavMarshall** [reactql/cli#67]
After installing and trying to create a new project there is an error on line 316 unexpected bracket after the comma .

I removed the comma and the new project was able to be created.

System:Windows 10
Install command:npm i -g reactql
Create new project command:reactql new

**Comment by leebenson** [comment]
Which version of Node are you using @eavMarshall ?

**Comment by leebenson** [comment]
http://node.green/#ES2017-features-trailing-commas-in-function-syntax

This works in the latest Node (8.4.0), but not the LTS version. Note that ReactQL will **only** work where `async/await` are available natively, which is Node 7.6+, so you'll need to bump your local Node installation anyway.

However, I'll fix this anyway so that the CLI runs successfully, and is able to quote the minimum required Node runtime when the version is < 7.6.

**Comment by leebenson** [comment]
Fix released in 4.5.6 - upgrade with `npm i -g reactql`
