### ISSUE TITLE
dotenv?

### ISSUE THREAD

**Issue by delmendo** [reactql/cli#71]
Do you have any plans on adding the use of dotenv ?  I end up using that to manage config changes in different environments.

**Comment by leebenson** [comment]
I think this is probably something that can remain in userland. The kit hard-wires `NODE_ENV` and `WEBPACK_CONFIG` in NPM run scripts, because they relate to specific build processes (and changing them wouldn't make a whole lot of sense.)

Additionally, it allows `HOST`, `PORT` and `SSL_PORT` for properly setting up the http(s) servers and GraphQL endpoint binding, but it doesn't enforce how those environment vars get into ReactQL. 

By default, they can just be passed on the CLI, but if you want to use `.env` you could include `require('dotenv').config();` in the `src/app.js` SERVER block to load them into `process.env.*`.

If you have a use case where the above wouldn't work with, let me know and I'd consider putting the above in core so it's pre-wired.

**Comment by josephdburdick** [comment]
@leebenson I've imported/required `dotenv` inside `app.js` and ran `dotenv.config();` both inside and outside the `if (SERVER) {` block but it's never changed the `process.env` object. Anything I may be missing here?

**Comment by leebenson** [comment]
Env vars are not currently working very well within ReactQL. That's because the Webpack config overwrites the default `process.env` with its own vars.

This will be improved in kit 3.0, which is coming down the pipe soon.

**Comment by slyshadoww** [comment]
@leebenson Hey man, thanks for your work, I wonder if you can tell me approximate eta of kit 3.0, thanks!

**Comment by leebenson** [comment]
@slyshadoww - I hate to keep giving ETAs, because my free time is all over the place at the moment, but as a route estimate I'd like to be done within the next 2 weeks.

Best bet is to follow [this comment on the thread](https://github.com/reactql/kit/issues/80#issuecomment-353722198)-- I'll be posting there first as soon as there's something released.

Kit 3 is a major overhaul to ReactQL- the CLI will disappear, and ReactQL will be installable as an NPM package built on top of a new Webpack framework called Launch.js. The link above explains more.
