### ISSUE TITLE
How to fix FOUC in dev mode?

### ISSUE THREAD

**Issue by mnpenner** [reactql/cli#75]
I'm seeing a FOUC (flash of unstyled content) in dev mode (`yarn start`). Normally this would be fine, but I need to calculate the widths of some elements as soon as they're mounted. If the CSS hasn't been loaded yet, this number comes out wrong.

How can I force the `<link rel="stylesheet" href="/assets/css/style.xxx.css"/>` tag to appear even in dev mode?

**Comment by klarstrup** [comment]
Did you try it on the dev mode ssr server?

**Comment by mnpenner** [comment]
@klarstrup Sorry, I'm not sure what that means. I'm literally running it with `yarn start` which runs

```sh
cross-env NODE_ENV=development WEBPACK_CONFIG=browser_dev webpack-dev-server
cross-env NODE_ENV=development WEBPACK_CONFIG=server_dev webpack --colors
```

In parallel. Is there another flag to enable SSR?

**Comment by leebenson** [comment]
@mnpenner - SSR mode should load automatically, alongside browser mode.

When you run `npm start` (or `yarn start` - never tried it with yarn) you should see something like:

<img width="719" alt="screen shot 2017-09-26 at 08 24 23" src="https://user-images.githubusercontent.com/719722/30847645-2e0a81d0-a294-11e7-85df-d3f9b6a39df4.png">

Going to http://localhost:8081 gives you a server-rendered view, which will prevent the FOUC since int his mode, all CSS is extracted out to `dist/assets/css/styles.css` and loaded before the main HTML.

**Comment by mnpenner** [comment]
Ah shoot. Sorry, I didn't even notice that. That doesn't do hot-reloading though does it? Ideally the full page would be served initially, and then patched thereafter. Regardless though, that should be good enough for my needs. I can press refresh on this one specific page.

I'm getting all kinds of issues on Windows right now. WDS seems to be locking all my files so I can't actually edit them when it's running anymore. I had this problem with ReactQL before, but it was working fine yesterday, and now it's not again. Anyway, I'll figure something out. Thanks!

**Comment by leebenson** [comment]
Nope, it doesn't hot-load in SSR. The purpose of :8081 is to mimic the server, but without minifying/optimising code, and with full source map support. The server automatically restarts on code changes, too.
