### ISSUE TITLE
LAN access for hot-reloading browser doesn't work

### ISSUE THREAD

**Issue by hellojere** [reactql/cli#76]
The hot-reloading version is not accessible through LAN, but the server-side version works just fine. 

Tried this with the latest version, fresh install, and couple machines. 

Don't really know how to debug this specific issue, but a solution would be highly appreciated, as this is a crucial part of my development workflow.

**Comment by leebenson** [comment]
You can set the environment variables `HOST` and `BROWSER_HOST` to `0.0.0.0` to bind to all local interfaces, instead of (the default) localhost.

See also https://github.com/reactql/kit/issues/100 for an enhancement using Docker.

**Comment by hellojere** [comment]
Thanks! Managed to get the page to load now, but the hot reloading is not working. Probably because of the following warning in the browser console: 

```
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
```

Appreciated if you can point a fix for this as well.

**Comment by leebenson** [comment]
https://github.com/reactql/kit/issues/99 - fix being pushed today

**Comment by leebenson** [comment]
re: port `8081` - yes, that's correct. When you `npm start` a ReactQL project, it will spawn both a browser hot-reload environment via Webpack dev server, as well as a server-side rendered version.

This simply tells the front-end that, unless the `PORT` env var tells it otherwise, it should point to `localhost:8081` in order to pass GraphQL queries to the SSR server that can handle them.
