### ISSUE TITLE
Impossible to build due to zopfli-webpack-plugin dep

### ISSUE THREAD

**Issue by Kamill90** [reactql/cli#99]
While trying to execute "npm run build" I get an error that zopfli-webpack-plugin module missing. 

After following suggestions to set environment: python 2.7, upgrade npm, node, install windows compile tools found in other issues, I cannot install zopfli-webpack-plugin. 
And I see that many developers have the same issue with this package. 
Is there any solution to walk around it?
(exact error below)

> npm install

> node-zopfli@2.0.2 install C:\Users\KamilL\Documents\Projekty\beers\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.2 and node@8.9.4 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)

**Comment by Kamill90** [comment]
Closing - the issue was with my computer environment.

**Comment by corydeppen** [comment]
@Kamill90 How did you resolve this? The node-zopfli issues are littered with folks unable to install the package.

**Comment by Kamill90** [comment]
I found out that on my another machine everything is ok. Somehow I managed to run it in both. New things learned. Thank you

**Comment by leebenson** [comment]
The vast majority of users having issues with node-zopfli will be because they don't have the [required binaries](https://github.com/pierreinglebert/node-zopfli#prerequisites-for-building) installed.

For anyone else reading that can't or doesn't want to install Python 2.x, a GCC compilers, etc - an easy solution is to just swap out node-zopfli for the [Compression Webpack Plugin](https://webpack.js.org/plugins/compression-webpack-plugin/) at https://github.com/reactql/kit/blob/master/kit/webpack/browser_prod.js#L128-L134

It doesn't install any binaries, at the cost of ~5% lesser compression.
